name: test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
        
      - uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: |
          yarn install

      - name: Build
        run: yarn build

      - name: Test client lib
        run: cd zk-chat-client-lib && yarn install && yarn build && yarn test && cd ..

      - name: Test server
        run: cd zk-chat-server-lib && yarn install && yarn build && yarn test && cd ..
